### ISSUE TITLE
Migrate to AndroidX Annotation

### ISSUE THREAD

**Issue by MGaetan89** [PiwikPRO/sdk-framework-android#2]
In the POM file of this repository, we can see that you are using the Annotations Support Library, instead of [AndroidX Annotation](https://developer.android.com/jetpack/androidx/releases/annotation):
https://github.com/PiwikPRO/sdk-framework-android/blob/eca6ab7d8d19377f5f125f2629ff477d29dfe22c/piwik-sdk-1.1.1.pom#L32-L37

Is it planned to migrate to AndroidX Annotation in a future release?

AndroidX libraries are Google's recommended libraries, as stated in the deprecated [Support Library documentation](https://developer.android.com/topic/libraries/support-library):
<img width="873" alt="Screenshot 2022-03-01 at 08 02 57" src="https://user-images.githubusercontent.com/1009664/156120894-49195e3d-1a28-4c54-9c77-b72f54dfa18a.png">

**Comment by MGaetan89** [comment]
Any update on this issue?

**Comment by MGaetan89** [comment]
FYI, with the stable release of Android Studio Chipmunk, there is a new feature to detect dependencies using old support libraries: https://android-developers.googleblog.com/2022/05/android-studio-chipmunk.html#:~:text=Build%20Analyzer%3A%20Check%20Jetifier

Piwik Pro is one of them:
![Screenshot from 2022-05-10 08-07-09](https://user-images.githubusercontent.com/1009664/167559664-106116a7-c166-4857-8ecd-998253e9ae73.png)

**Comment by harmasz** [comment]
Updating dependencies is currently on our agenda and we will be looking into bumping them in the next couple of weeks.

**Comment by MGaetan89** [comment]
Any news on this?

**Comment by MGaetan89** [comment]
It looks like this was addressed in [1.1.6](https://github.com/PiwikPRO/sdk-framework-android/releases/tag/1.1.6). Thanks!
