### ISSUE TITLE
Add missing dependency to `com.google.android.gms:play-services-ads-identifier`

### ISSUE THREAD

**Issue by MGaetan89** [PiwikPRO/sdk-framework-android#3]
Recent releases of `com.google.android.gms:play-services-basement` no longer depend on `com.google.android.gms:play-services-ads-identifier`, preventing access to `AdvertisingIdClient`, which seems to be used by Piwik PRO.

Depending on how you currently use `com.google.android.gms:play-services-basement`, you might need to either:
- add a dependency to `com.google.android.gms:play-services-ads-identifier`
- replace `com.google.android.gms:play-services-basement` with `com.google.android.gms:play-services-ads-identifier`

The dependency currently used is declared in the POM file in this repository:
https://github.com/PiwikPRO/sdk-framework-android/blob/eca6ab7d8d19377f5f125f2629ff477d29dfe22c/piwik-sdk-1.1.1.pom#L44-L49

**Comment by MGaetan89** [comment]
Any update on this issue?

**Comment by harmasz** [comment]
Sorry for the long wait @MGaetan89. We are in the process of refactoring our Android SDK and we will be working on this in the coming weeks.

**Comment by MGaetan89** [comment]
It looks like this was addressed in [1.1.6](https://github.com/PiwikPRO/sdk-framework-android/releases/tag/1.1.6). Thanks!
